services:
  - type: web
    name: menu-x-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://menu-x-frontend.onrender.com,http://localhost:3000
      - key: QR_BASE_URL
        value: https://menu-x-frontend.onrender.com/menu
      - key: LOG_LEVEL
        value: INFO
      - key: SECURITY_LOG_LEVEL
        value: WARN
      - key: SQL_LOG_LEVEL
        value: WARN