services:
  - type: web
    name: menu-x-backend
    runtime: java17
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -jar target/menu-x-backend-1.0.0.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        value: AIzaSyAuWkC4FLccs0EZs0prOufuBk2ojWaCb2E
      - key: CORS_ALLOWED_ORIGINS
        value: https://menux-frontend.onrender.com,http://localhost:3000
      - key: QR_BASE_URL
        value: https://menux-frontend.onrender.com/menu
      - key: LOG_LEVEL
        value: INFO
      - key: SECURITY_LOG_LEVEL
        value: WARN
      - key: SQL_LOG_LEVEL
        value: WARN
