# Supabase Configuration for Menu.X
spring:
  application:
    name: menu-x-backend

  # Supabase Database Configuration
  datasource:
    url: jdbc:postgresql://db.pcwuvpjuysurnguqlzok.supabase.co:5432/postgres
    username: postgres
    password: ${DB_PASSWORD} # Simplified for Render
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  cachePrepStmts: false

  # Corrected JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Application Configuration
app:
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days

  # CORS Configuration
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  # QR Code Configuration
  qr:
    base-url: ${QR_BASE_URL}
    image-format: PNG
    width: 300
    height: 300

  # AI Configuration - Gemini
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta
      model: gemini-pro

# Logging Configuration
logging:
  level:
    com.menux: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html