# Supabase Configuration for Menu.X
spring:
  application:
    name: menu-x-backend
  
  # Supabase Database Configuration
  datasource:
    url: jdbc:postgresql://db.pcwuvpjuysurnguqlzok.supabase.co:5432/postgres
    username: postgres
    password: ${SUPABASE_DB_PASSWORD:your_supabase_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Application Configuration
app:
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:MenuXSecretKey2024ForProductionUseStrongerKey}
    expiration: 86400000  # 24 hours
    refresh-expiration: 604800000  # 7 days
    
  # CORS Configuration
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    
  # QR Code Configuration
  qr:
    base-url: http://localhost:3000/menu
    image-format: PNG
    width: 300
    height: 300
    
  # AI Configuration - Gemini
  ai:
    gemini:
      api-key: AIzaSyAuWkC4FLccs0EZs0prOufuBk2ojWaCb2E
      base-url: https://generativelanguage.googleapis.com/v1beta
      model: gemini-pro

# Logging Configuration
logging:
  level:
    com.menux: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
